name: Android CI/CD (Build APK)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    # स्टेप 1: रनर के ग्लोबल gradle से आपके प्रोजेक्ट के लिए सही wrapper जेनरेट करना
    - name: Generate Gradle Wrapper
      run: gradle wrapper

    # स्टेप 2: जेनरेट हुई gradlew फ़ाइल को एग्जीक्यूट करने की परमिशन देना
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    # स्टेप 3: प्रोजेक्ट के अपने सही gradlew से बिल्ड करना और KSP एरर को बाईपास करना
    - name: Build Debug APK
      run: ./gradlew assembleDebug --no-daemon -Dorg.gradle.jvmargs="-Djava.awt.headless=true"
